-include ../../Rules.make

MATRIX_WEB_DIR = "webpages"

default:
	@echo "Nothing to build"

clean:
	@echo "Nothing to clean"

install:
	@install -d ${DESTDIR}/${MATRIX_WEB_DIR}
	@cp -rf * ${DESTDIR}/${MATRIX_WEB_DIR}
